app/routes/main_routes.py
from argparse import Namespace
from html import unescape
from flask import Blueprint,session,render_template,redirect,url_for,request,jsonify, send_from_directory,current_app
from functions import get_db,UploadFileForm,get_file_names_without_extensions,get_app,t_types,get_users,check_files,convert_name
from signature import sign_pdf
from unidecode import unidecode
from werkzeug.utils import secure_filename

import argparse
import base64
import json
import os
import tempfile
import traceback
import logging

parser = argparse.ArgumentParser(description="DALİŞ")
logging.basicConfig(filename='/home/BerkeErtep/mysite/myapp.log', level=logging.INFO)

main_bp = Blueprint('main', __name__)

@main_bp.route('/index', methods=['GET','POST'])
@main_bp.route('/', methods=['GET','POST'])
def dashboard():
    form = UploadFileForm()
    if 'email' in session:
        tckn = session["tckn"]
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT templates FROM Users WHERE tckn = ?", (tckn,))
        result = cursor.fetchone()
        
        templates= [] if result[0] == None else json.loads(result[0])
        session["template"]=templates
        
        return render_template("index.html",session=session,json=json,t_type= t_types,
        form=form,check_files=check_files,
        convert_name=convert_name,enumerate=enumerate,str=str,
        len=len)
    return redirect(url_for('auth.login'))


@main_bp.route('/signature',methods=['GET','POST'])
def signature():
    form = UploadFileForm()
    if request.method == 'GET':
        return render_template("signature.html",form=form)
    else:

        if form.validate_on_submit():
            file = form.file.data
            file.save(os.path.join(os.path.abspath(os.path.dirname(__file__)),"../static/files",secure_filename(file.filename)))
        return ('',204)

@main_bp.route('/save_superadmin_signature', methods=['POST'])
def save_superadminsignature():
    allowed_roles = ["SuperAdmin","Admin"]
    if not "email" in session or not session.get("Role") in allowed_roles:
        return jsonify({"Error":"Permission Denied"})
    
    try:
        data = request.get_json()
        signature_data = data.get('signature')
        filename = f"{current_app.config['CWD']}/app/static/files/signature{secure_filename(data.get('filename'))}.png"
        contract = data.get('contract')
        tckn = data.get('tckn')
        conn = get_db()
        cursor = conn.cursor()
        #contractPath contractName startX startY width height

        contract_info = cursor.execute('SELECT * from contractPaths WHERE contractPath = ?', (contract,)).fetchone()
        pdfHeight,startX,startY,width,height,page_num = round(float(contract_info[7])),int(contract_info[2]),int(contract_info[3]),int(contract_info[4]),int(contract_info[5]),int(contract_info[6])
        with open(filename, 'wb') as f:
            f.write(base64.b64decode(signature_data.split(',')[1]))

        args = Namespace(
            pdf=contract,
            signature=filename,
            date=False,
            output =f"{current_app.config['CWD']}/app/static/superadmin_contracts/contract{secure_filename(data.get('filename') + data.get('mail'))}.pdf",
            coords=f"{page_num}x{startX}x{pdfHeight-height -startY}x{width}x{height}"
        )
        result = sign_pdf(args)
        # change contractSigned status on database
        cursor.execute("SELECT templates FROM Users WHERE tckn = ?", (tckn,))
        templates = cursor.fetchone()
        templates = json.loads(templates[0])
        template_id = data.get('template_id')
        new_templates = []
        for template in templates:
            if template.get("template_id") == int(template_id):
                template['superadmin_sign'] = 1
                new_templates.append(template)
            else:

                new_templates.append(template)

        cursor.execute("UPDATE Users SET templates = ? WHERE tckn = ?", (json.dumps(templates), tckn))
        conn.commit()
        conn.close()
        return jsonify({'message': 'Signature saved successfully'}), 200
    except Exception as e:
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500
@main_bp.route('/save_signature', methods=['POST'])
def save_signature():

    try:
        data = request.get_json()
        signature_data = data.get('signature')
        filename = f"{current_app.config['CWD']}/app/static/files/signature{secure_filename(data.get('filename'))}.png"
        contract = data.get('contract')
        logging.info("Contract: {}".format(contract))
        tckn = data.get('tckn')
        logging.info("TCKN: {}".format(tckn))
        conn = get_db()
        cursor = conn.cursor()
        #contractPath contractName startX startY width height

        contract_info = cursor.execute('SELECT * from contractPaths WHERE contractPath = ?', (contract,)).fetchone()
        pdfHeight,startX,startY,width,height,page_num = round(float(contract_info[7])),int(contract_info[2]),int(contract_info[3]),int(contract_info[4]),int(contract_info[5]),int(contract_info[6])
        with open(filename, 'wb') as f:
            f.write(base64.b64decode(signature_data.split(',')[1]))

        args = Namespace(
            pdf=contract,
            signature=filename,
            date=False,
            output =f"{current_app.config['CWD']}/app/static/customer_contracts/contract{contract.split('/')[-1].split('.')[0]}{secure_filename(data.get('filename'))}.pdf",
            coords=f"{page_num}x{startX}x{pdfHeight-height -startY}x{width}x{height}"
        )
        result = sign_pdf(args)
        logging.info("signed contract file saved")
        # change contractSigned status on database
        cursor.execute("SELECT templates FROM Users WHERE tckn = ?", (tckn,))
        templates = cursor.fetchone()

        # Ensure that templates is a list, not None
        if templates:
            templates = json.loads(templates[0])
        else:
            templates = []  # In case the templates field is empty

        template_id = data.get('template_id')
        new_templates = []

        # Process templates and update contract status
        for template in templates:
            if template.get("template_id") == int(template_id):
                new_contracts = []

                for cont in template.get("contract"):
                    if cont.get("contract") == contract:
                        cont["signed"] = 1
                    new_contracts.append(cont)

                count = len([x for x in new_contracts if x['signed'] == 1])

                if count == len(template.get("contract")):
                    template["contractSigned"] = 1

                template['contract'] = new_contracts
                new_templates.append(template)  # Add the updated template to new_templates
            else:
                new_templates.append(template)  # Keep unchanged templates as they are

        # Update the templates field with new templates
        templates = new_templates  # Assign new_templates back to templates

        # Log the updated templates
        logging.info("Templates after signature update {}".format(templates))

        # Update the database with the modified templates
        cursor.execute("UPDATE Users SET templates = ? WHERE tckn = ?", (json.dumps(templates), tckn))
        conn.commit()
        conn.close()
        return jsonify({'message': 'Signature saved successfully'}), 200
    except Exception as e:
        
        logging.info(traceback.print_exc())
        return jsonify({'error': str(e)}), 500


@main_bp.route('/save_contract',methods=['GET','POST'])
def save_contract():
    allowed_roles = ["SuperAdmin","Admin"]
    if not "email" in session or not session.get("Role") in allowed_roles:
        return jsonify({"Error":"Permission Denied"})
    
    form = UploadFileForm()
    if request.method == 'GET':
        return render_template("signature.html",form=form)
    else:

        if form.validate_on_submit():
            file = form.file.data
            file.save(os.path.join(os.path.abspath(os.path.dirname(__file__)),"../static/contracts",secure_filename(file.filename)))
            return ('',204)

        else:
            data = request.get_json()
            pdf_data = f"{current_app.config['CWD']}/app/static/contracts/{secure_filename(data['filename'])}"

            conn = get_db()
            cursor = conn.cursor()


            startY = int(data['startY'])
            startX = int(data['startX'])
            width = int(data['width'])
            height = int(data['height'])
            page_num = data['page_num']
            signature_path = "signature.png"

            output = data.get('output', None)


            cursor.execute("INSERT OR REPLACE INTO contractPaths (contractPath,contractName,startX,startY,width,height,page,pdfHeight) VALUES (?,?,?,?,?,?,?,?)",(pdf_data,secure_filename(data['filename']),startX,startY,width,height,page_num,data['pdfHeight']))
            conn.commit()
            conn.close()

            return jsonify({"status":"saved"})


@main_bp.route('/api/delete_file')
def delete_file():
    allowed_roles = ["SuperAdmin","Admin","Customer"]
    if not "email" in session or not session.get("Role") in allowed_roles:
        return jsonify({"Error":"Permission Denied"})
    tckn = request.args.get('tckn')
    conn = get_db()
    cursor = conn.cursor()
    cursor.execute("SELECT templates FROM Users WHERE tckn = ?", (tckn,))
    templates = cursor.fetchone()
    template_id = request.args.get("template_id")
    file_path = request.args.get("file_path")
    new_templates = []
    for template in json.loads(templates[0]):
        if template.get("template_id") == int(template_id):
            files = template["files"]
            [files.remove(x)  for x in files if file_path in x]
            # Example usage
            folder_path = f"{current_app.config['CWD']}/app/static/files"

app/templates/addadmin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/css/style.css" />
    <title>Gerekli Dosyalar</title>
</head>
<body>
    <body>

        <div class="container">
            {%with%}
            {% include 'navigator.html' %}
            {%endwith%}
    
            <div class="add-filename">
                <div class="title">
                    <h1>Admin Üye Ekle</h1>
                </div>
                <form action="/addadmin" method="post">
                    <input type="text" class="addfileinput" name="tckn" placeholder="Tc Kimlik Numarası">

                    <button type="submit" class="update-button button button-primary button-lg">Ekle</button>
                </form>
                {%if success==True%}
                <div class="success">
                    <h3>Başarılı</h3>
                </div>
                {%endif%}
            </div>
        </div>
    </body>
</body>
</html>

app/templates/addtemplate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template Ekle</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="static/css/style.css" />
    <script src="https://kit.fontawesome.com/be0ab69668.js" crossorigin="anonymous"></script>
</head>
<body>        
    <div class="container">
        {%with%}
        {% include 'navigator.html' %}
        {%endwith%}

        <div class="users" id="users">
            <div id="overlay"></div>
            <div class="users-container">
    
                <table >
                    <tbody id="user_information">
                        <tr>
                            <th>Full Name</th>                                
                            <th>TCKN</th>                                
                            <th>Email</th>
                            <th>Phone Number</th>
                            <th>Role</th>
                            <th>Parent Roles</th>
                            <th>Template</th>
                        </tr>
                        {% for user in users %}
                        <tr>
         
                            <td>{{ user[0] }} {{ user[1] }}</td>
                            <td>{{ user[2] }}</td>
                            <td>{{ user[3] }}</td>
                            <td>{{ user[4] }}</td>
                            <td>{{ user[7] }}</td>
                            <td>{{ user[8] }}</td>
                            <td>
                                <div class="modal" id="modal{{ user[2] }}">
                                    <div class="customertemplate-container">
                                        <div class="close-button" data-close-button>
                                            <i class="fa-solid fa-xmark"></i>
                                        </div>
                                        <form id="templateForm{{ user[2] }}" name="templateForm{{ user[2] }}" action="" method="POST">
                                            <div class="description-background">
                                                <label for="description">Açıklama:</label>
                                                <textarea class="addtemplate-description" placeholder="Açıklama girin" id="description" name="description"></textarea>
    
                                            </div>
                                            <div class="template-type">
                                                <label for="templateType">Template Türü:</label><br>
                                                <select id="templateType" class="templateType" name="type">
                                                    <option value="81A">81A Ön Onaysız</option>
                                                    <option value="81A">81A Ön Onaylı</option>
                                                    <option value="MAVIKART">MAVIKART</option>
                                                    <option value="AUSBILDUNG">AUSBILDUNG</option>
                                                    <option value="SCHENGEN">SCHENGEN</option>
                                                    <option value="19C">19C</option>
                                                </select>
                                            </div>
                                            <div class="contract">
                                                <label for="contract">Sözleşme:</label>
                                                <i class="fa-solid fa-plus" style="font-size:20px;" onclick="addContractSelector('{{ user[2] }}')"></i>
                                                <br>
                                                <div class="innercontract" id="innercontract{{ user[2] }}">
                                                    <div class="contractselectors" id="contractselectors{{ user[2] }}">
                                                        <select name="contract0" id="contracts0" class="contracts">
                                                            {% for contract in contracts %}
                                                            <option value="{{ contract[0] }}">{{ contract[1] }}</option>
                                                            {% endfor %}
                                                        </select>
                                                    </div>
    
                                                    <a href="{{ url_for('main.save_contract') }}">Sözleşme Ekle</a>
                                                </div>
                                            </div>

                                            <button class="update-button button button-primary button-lg" id="update-button"
                                            type="submit">Ekle</button>
                                                <input type="hidden" id="tckn" name="tckn" value="{{ user[2] }}">
                                                <input type="hidden" id="incharge" name="incharge" value='["{{ session["email"] }}"]'><br>
                                                <input type="hidden" id="files" name="files" value='[]'><br>                                
                                                <input type="hidden" id="tasks" name="tasks" value='[]'><br>
                                                <input type="hidden" id="comments" name="comments" value='[]'><br>
                                        </form>
            
                                    </div>
                                </div>
                                <div data-modal-target="#modal{{ user[2] }}" class="home-todo-content addtemplate">Template Ekle</div>
                            </td>
                            <script>
                                document.getElementById("templateForm{{user[2]}}").addEventListener("submit", function(event) {
                                    event.preventDefault();
                                    const formData = new FormData(this);
                                    const searchParams = new URLSearchParams(formData).toString();
                                    
                                    // Now you can send this URL-encoded parameters to your backend via AJAX
                                    console.log(searchParams);
                                    console.log( '/api/add_template?'+ searchParams);
                                    // Example AJAX request
                                    $.ajax({
                                        url: '/api/add_template?'+ searchParams,
                                        type: 'POST',
                                        success: function(response) {
                                            //reload page
                                            location.reload();
    
    
                                        },
                                        error: function(xhr, status, error) {
                                            console.error(error);
                                        }
                                });
                            });
                            // Attach event listeners after elements have been appended
                       
                                </script>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <script>

        $(".addtemplate").on("click", function () {
            const modal = document.querySelector($(this).data("modal-target"));
            openModal(modal);
        });

        $('#overlay').on('click', () => {
            const modals = document.querySelectorAll('.modal.active');
            modals.forEach(modal => {
                closeModal(modal);
            });
        });

        $("#addtemplate").on("click", '[data-close-button]', function () {
            const modal = $(this).closest('.modal')[0];
            closeModal(modal);
        });

        function openModal(modal) {
            if (modal == null) return;
            modal.classList.add('active');
            $('#overlay').addClass('active');
        }

        function closeModal(modal) {
            if (modal == null) return;
            modal.classList.remove('active');
            $('#overlay').removeClass('active');
        }

        function addContractSelector(userId) {
            var newselect = document.createElement("select");
            var nameid = document.querySelectorAll("#contractselectors" + userId + " .contracts").length;
            newselect.name = "contract" + nameid;
            newselect.id = "contracts" + nameid;
            newselect.className = "contracts";
            var options = {{ contracts|tojson }};
            options.forEach(function(optionText) {
                var option = document.createElement("option");
                option.text = optionText[1];
                option.value = optionText[0]; // Set value if needed
                newselect.add(option);
            });

            $("#contractselectors" + userId).append(newselect);
        }
    </script>
    
</body>
</html>

app/templates/filenames.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/css/style.css" />
    <title>Gerekli Dosyalar</title>
</head>
<body>
    <body>

        <div class="container">
            {%with%}
            {% include 'navigator.html' %}
            {%endwith%}
    
            <div class="add-filename">
                <div class="title">
                    <h1>Gerekli Dosya Ekleme</h1>
                </div>
                <form action="/filenames" method="post">
                    <input type="text" class="addfileinput" name="fileName" placeholder="Dosya Adı">
                    <label>81A Ön Onaysız - 81A Ön Onaylı - MAVIKART - AUSBILDUNG - SCHENGEN - 19C</label>
                    <input type="text" class="addfileinput" name="templateType" placeholder="Dosya Türü (ör: MAVIKART, büyük harf ile yazınız) ">

                    <div class="checkbox">

                        <input name="optional" type="checkbox" >
                        <label for="optional" >Opsiyonel</label>
                    </div>
                    <button type="submit" class="update-button button button-primary button-lg">Ekle</button>
                </form>
                {%if success==True%}
                <div class="success">
                    <h3>Başarılı</h3>
                </div>
                {%endif%}
            </div>
        </div>
    </body>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Anasayfa</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="static/css/style.css" />
</head>

<body>

    <div class="container">
        <nav class="navigator">
            <div class="navigator-logo">
            </div>
            <div class="navigator-links">
                {%if session.get("role") in ["Admin","SuperAdmin"]%}
                <a class="nav-button" href="/admin">Admin Paneli</a>
                {%endif%}

                <a class="nav-button" href="/">Anasayfa</a>

                <a class="nav-button" href="/logout">Çıkış Yap</a>
                <div class="nav-button">
                    <form action="" class="filter">
                        <input type="checkbox" name="inprogress-filter" id="inprogress-filter" checked>
                        <label for="inprogress-filter">
                            Yapılacak
                        </label>
                        <input type="checkbox" name="done-filter" id="done-filter" checked>
                        <label for="done-filter">
                            Yapıldı
                        </label>
                    </form>
                </div>
                <input type="text" class="searchbar nav-button" id="searchInput" placeholder="Search...">
            </div>
        </nav>
        <div class="templates">
            <div id="inprogress" class="home-inprogress template">
    
                <div class="home-title">
                    <h1 class="home-heading">
                        <span>Yapılacak</span>
                        <br />
                    </h1>
                </div>
                <div id="inprogress-content" class="home-inprogress-content template-content">
    
                    {% for template in session["template"] %}
    
                    {%if template.get("templateStatus") == 0 %}
                    {% with 
                        template=template,
                        session=session,
                        json=json,
                        t_type=t_type,
                        form=form,
                        check_files=check_files,
                        convert_name=convert_name,
                        enumerate=enumerate,
                        str=str,
                        len=len
                    %}
                        {% include 'modal.html' %}
                    {% endwith %}
                    

                    {%endif%}
                    {% endfor %}
    

                </div>
    
            </div>
            <div id="done" class="home-done template">
    
                <div class="home-title">
                    <h1 class="home-heading">
                        <span>Yapıldı</span>
                        <br />
                    </h1>
                </div>
                <div id="done-content" class="home-done-content template-content">
    
                    {% for template in session["template"] %}
                    {%if template.get("templateStatus") == 1 %}
                    {% with 
                        template=template,
                        session=session,
                        json=json,
                        t_type=t_type,
                        form=form,
                        check_files=check_files,
                        convert_name=convert_name,
                        enumerate=enumerate,
                        str=str,
                        len=len
                    %}
                        {% include 'modal.html' %}
                    {% endwith %}
                    {%endif%}
                    {% endfor %}
    
                </div>
    
            </div>
        </div>

        <div id="overlay"></div>
        <script>
      
            // Event delegation for opening modal
            $(document).on("click", '[data-modal-target]', function () {
                const modal = document.getElementById($(this).data("modalTarget"));

                openModal(modal);
            });

            // Event delegation for closing modal
            $('#overlay').on('click', () => {
                const modals = document.querySelectorAll('.modal.active');
                modals.forEach(modal => {
                    closeModal(modal);
                });
            });

            // Event delegation for closing modal
            $(document).on("click", '[data-close-button]', function () {
                const modal = $(this).closest('.modal')[0];
                closeModal(modal);
            });

            // Function to open modal
            function openModal(modal) {
                if (modal == null) return;
                modal.classList.add('active');
                $('#overlay').addClass('active');
            }

            // Function to close modal
            function closeModal(modal) {
                if (modal == null) return;
                modal.classList.remove('active');
                $('#overlay').removeClass('active');
            }

        </script>

        <script>
            // Add event listeners to the checkboxes
        const inprogressFilterCheckbox = document.getElementById('inprogress-filter');
        const doneFilterCheckbox = document.getElementById('done-filter');

        inprogressFilterCheckbox.addEventListener('change', () => {
        const homeinprogress = document.querySelector('.home-inprogress');
        if (!inprogressFilterCheckbox.checked) {
        homeinprogress.style.display = 'none';
        } else {
        homeinprogress.style.display = 'flex';
        }
        });

        doneFilterCheckbox.addEventListener('change', () => {
        const homeDone = document.querySelector('.home-done');
        if (!doneFilterCheckbox.checked) {
        homeDone.style.display = 'none';
        } else {
        homeDone.style.display = 'flex';
        }
        });

        // Get the search input field
        const searchInput = document.getElementById('searchInput');

        // Add event listener for input changes
        searchInput.addEventListener('input', function() {
        // Get the search query
        const searchQuery = this.value.trim().toLowerCase();

        // Get the elements to search within
        const templates = document.querySelectorAll('.templates .draggable-item');

        // Iterate over the elements and hide/show based on search query
        templates.forEach(template => {
        const name = template.querySelector('h3').textContent.toLowerCase();
        if (name.includes(searchQuery)) {
        template.style.display = 'block'; // Show the element
        } else {
        template.style.display = 'none'; // Hide the element
        }
        });
        });

        </script>
    </div>
</body>

</html>

app/templates/kvkk.html
<div class="input-group kvkk_acceptance">
    <input type="checkbox" id="kvkk_acceptance" name="kvkk_acceptance" required>
    <label for="kvkk_acceptance">KVKK'yı kabul ediyorum</label>
</div>
<div id="overlay"></div>

<div id="kvkk_popup" class="popup">
    <div class="popup-content">
        <span class="close-button" onclick="closePopup()" style="font-size: 2rem;color:white;">&times;</span>
        <iframe src="{{ url_for('static', filename='cerezlere_dair_aydinlatma_metni.pdf') }}"
            style="width: 100%; height: 500px;" frameborder="0"></iframe>
    </div>
</div>

<script>
    // Function to display KVKK popup
    function showPopup() {
        var popup = document.getElementById("kvkk_popup");
        popup.style.display = "block";
        $('#overlay').addClass('active');

    }

    // Function to close KVKK popup
    function closePopup() {
        var popup = document.getElementById("kvkk_popup");
        popup.style.display = "none";
        $('#overlay').removeClass('active');

    }
    $('#overlay').on('click', () => {
        var popup = document.getElementById("kvkk_popup");
        popup.style.display = "none";
        $('#overlay').removeClass('active');

    });
    // Event listener for checkbox
    document.getElementById("kvkk_acceptance").addEventListener("change", function () {
        if (this.checked) {
            showPopup(); // Display popup when checkbox is checked
        } else {
            closePopup(); // Close popup when checkbox is unchecked
        }
    });
</script>